SIMULATOR_PORT = 8080
FRAME_RATE = 24
SERIAL_PORT = '/dev/ttyAMA0'
SERIAL_BAUD = 9600


LILYPADS = 6
PETALS = 12
LEDS_PER_PETAL = 60
LEDS = PETALS * LEDS_PER_PETAL

ATTRACT_PATH = './assets/attract'
REWARD_PATH = './assets/reward'

MIN_ATTRACT_FRAMES = FRAME_RATE * 30
MAX_ATTRACT_FRAMES = FRAME_RATE * 45
ATTRACT_LILYPAD_RATE = 2
ATTRACT_LILYPAD_HUE_STEP = 1.0 / (FRAME_RATE * 3)
ATTRACT_LILYPAD_BRIGHTNESS = 0.5

FOREPLAY_FRAMES = FRAME_RATE * 30
BLACK_FRAMES = FRAME_RATE * 10

BLOSSOM_RATE = 60
BLOSSOM_OPEN_TIME = 15
BLOSSOM_SHOW_TIME = 60
BLOSSOM_CLOSE_TIME = 15

TEST_FRAMES = FRAME_RATE * 2
