SIMULATOR_PORT = 8080
FRAME_RATE = 30


NUM_LILYPADS = 6
PETALS = 12
LEDS_PER_PETAL = 60
LEDS = PETALS * LEDS_PER_PETAL

ATTRACT_PATH = './assets/attract'
REWARD_PATH = './assets/reward'

SHOW_TIME = 300
REWARD_RATE = 6
