SIMULATOR_PORT = 8080
FRAME_RATE = 24


LILYPADS = 6
PETALS = 12
LEDS_PER_PETAL = 60
LEDS = PETALS * LEDS_PER_PETAL

ATTRACT_PATH = './assets/attract'
REWARD_PATH = './assets/reward'

MIN_ATTRACT_FRAMES = FRAME_RATE * 30 
MAX_ATTRACT_FRAMES = FRAME_RATE * 60
ATTRACT_LILYPAD_RATE = 2
ATTRACT_LILYPAD_HUE_STEP = 1.0 / (FRAME_RATE * 3)
ATTRACT_LILYPAD_BRIGHTNESS = 0.5

FOREPLAY_FRAMES = FRAME_RATE * 10

BLOSSOM_MOVE_TIME = 90
BLOSSOM_SHOW_TIME = 90

TEST_FRAMES = FRAME_RATE * 2
